### ISSUE TITLE
Board icons broken with JS disabled

### ISSUE THREAD

**Issue by kaizushi** [SMFTricks/NameX#1]
I am having an issue with this theme, and technically others where board icons are broken without JS. This is problematic, and a bit dissapointing because this theme otherwise works quite well like this. I work for clients who have customers themselves which cannot use JS.

The icons are clearly broken because of missing unicodes. I wonder if anyone knows how these can be added to the theme in some fashion with JS? This would be good to know, as the unicodes exist on my systems and such where I am testing it.

It is simply that for some reason it only renders the board icons unicode when JS is enabled. 

Does anyone have any ideas on how I might modify the theme to rectify this?

**Comment by DiegoAndresCortes** [comment]
The fonts can be loaded locally so I’m not sure why the icons would be broken? Wouldn’t it cause issues with ALL the icons?
Could you share some screenshots and/or examples?
