### ISSUE TITLE
Menu sign out button broken

### ISSUE THREAD

**Issue by dennisb1** [SMFTricks/NameX#2]
The sign out button in the menu is broken, it is pointing to the wrong url. 

For example;

/forum/index.php?action=loginf9bc38c48=754aafd2bdae4e67cb3a40

should be action=logout;randomnumberhere

**Comment by DiegoAndresCortes** [comment]
Where exactly? The profile menu?

**Comment by dennisb1** [comment]
The one with this option;
Add Log out, Log in and Register buttons to the main menu:

**Comment by DiegoAndresCortes** [comment]
The theme itself doesn't add those buttons, it just provides 'true' to a predefined variable in SMF.
The URL looks fine in SMF: 
https://github.com/SimpleMachines/SMF/blob/a0ca0ddd807ed94ee14b060a042dc27373bf2aed/Sources/Subs.php#L5558-L5565

Check if your Subs.php somehow has this wrong.

**Comment by dennisb1** [comment]
Oh... 
Thats explains alot, my development SMF is still using 2.1.1, seems like that was a bug in SMF

https://github.com/SimpleMachines/SMF/blob/v2.1.1/Sources/Subs.php#L5536-L5542

Sorry for this!

**Comment by DiegoAndresCortes** [comment]
No problem! Glad we figured it out.
