### ISSUE TITLE
login bug when guest view disabled

### ISSUE THREAD

**Issue by dennisb1** [SMFTricks/NameX#3]
There is a login bug that took me a while to figure out, had to disable all mods and more to rule things out.

When you have this theme as default and you have Forum guests can view the forum disabled you can't login anymore after the second time.

To reproduce:
- Set NameX as default theme (and no user selectable)
- Turn guest view off 
- Logout
- Login

When you then want to login again you get:
`Token verification failed. Please go back and try again`

Cookies remove wont help at all, refresh not, reboot not, just nothing.

Use a other browser or privacy window will work.

Work around 1 if you want guest view to stay off:
- Set default to Curve2 (default SMF)
- Turn guest view off
- Enable for your account NameX 
- Logout
- Login

Work around 2 (what i did for now):
- Set default to NameX
- Turn guest view on
- Login/logout works perfectly
-- Downside, people have to press manualy on login since no boards are available for guests

Then everything is working fine to log back in without any issues

**Comment by DiegoAndresCortes** [comment]
Only workaround I've been able to get is disabling mode and variants selection for guests when _Allow guests to browse the forum_  option is enabled.
I do not know what causes this issue, potentially not fixable in the current implementation of the theme functions. (theme hooks are not native).

**Comment by dennisb1** [comment]
What are you suggesting? That if you turn off color and dark mode selection this bug isn’t happening?

**Comment by DiegoAndresCortes** [comment]
Turning it off for guests, yes.

It's the only workaround at the moment.

**Comment by dennisb1** [comment]
That’s not a big issue. Guests aren’t allowed anyway since the setting “guest can view the forum” is already disabled in the first place. (When this bug is happening)

but is there a setting to turn this off for not logged in users at this time?

**Comment by DiegoAndresCortes** [comment]
No option for that at this time, perhaps in the future.
Easiest way is to do it manually is to edit these functions:
https://github.com/SMFTricks/NameX/blob/0ad25b2787066a6d593e790cd3368e5f2e872256/themecustoms/Init.php#L106

```
        public static function variants(array &$variants) : void {
                 global $user_info;

                if (!empty($user_info[‘is_guest])
                        return;
                …
```

and the same for this one
https://github.com/SMFTricks/NameX/blob/0ad25b2787066a6d593e790cd3368e5f2e872256/themecustoms/Init.php#L126

**Comment by DiegoAndresCortes** [comment]
I've added a new commit to fix it and disable variants or dark mode when the user hits a 'wall' because the forum doesn't allow guests to browse the forum OR the forum is on maintenance mode.

New update should be available tuesday, or next week (I don't want to trigger it manually for all themes, it's much work).

**Comment by dennisb1** [comment]
Is it correct i don't see this change yet on github at this moment as a commit? 

I have done the manual change as you suggested to test but then i get a error 500 instantly 
For my quick fix (and to have guest view disabled) i have turned off the color/darkmode settings for users,this also fixes it for now as you suggested it. 

Excellent your picking this up so quickly, really appreciated.

**Comment by DiegoAndresCortes** [comment]
I triggered it manually for this theme. See the change:
https://github.com/SMFTricks/NameX/commit/b0f4102569d65943fbcb1a3a9a2d87cf5898c814

**Comment by dennisb1** [comment]
Excellent work sir! It works excellent as it should. 😄

**Comment by DiegoAndresCortes** [comment]
Awesome!
I'll likely leave this as the definitive solution (at least for SMF 2.1.x)

Perhaps in SMF 3.0 I'll investigate a solution for the issue, or rewrite some parts of my code.
Thanks!

**Comment by DiegoAndresCortes** [comment]
I've been doing some tests on this while doing a big update on the themes skeleton, and so far it seems fixed but I'll keep testing.
New update for all themes might be ready early next month.
